// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/session.proto

package com.github.fedragon.protobuffying.protocol;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SessionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuffying.Session)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string start = 2;</code>
     */
    boolean hasStart();
    /**
     * <code>required string start = 2;</code>
     */
    java.lang.String getStart();
    /**
     * <code>required string start = 2;</code>
     */
    com.google.protobuf.ByteString
        getStartBytes();

    /**
     * <code>required string end = 3;</code>
     */
    boolean hasEnd();
    /**
     * <code>required string end = 3;</code>
     */
    java.lang.String getEnd();
    /**
     * <code>required string end = 3;</code>
     */
    com.google.protobuf.ByteString
        getEndBytes();
  }
  /**
   * Protobuf type {@code protobuffying.Session}
   */
  public static final class Session extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuffying.Session)
      SessionOrBuilder {
    // Use Session.newBuilder() to construct.
    private Session(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Session(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Session defaultInstance;
    public static Session getDefaultInstance() {
      return defaultInstance;
    }

    public Session getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Session(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              start_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              end_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.fedragon.protobuffying.protocol.Protocol.internal_static_protobuffying_Session_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.fedragon.protobuffying.protocol.Protocol.internal_static_protobuffying_Session_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.fedragon.protobuffying.protocol.Protocol.Session.class, com.github.fedragon.protobuffying.protocol.Protocol.Session.Builder.class);
    }

    public static com.google.protobuf.Parser<Session> PARSER =
        new com.google.protobuf.AbstractParser<Session>() {
      public Session parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Session(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Session> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int START_FIELD_NUMBER = 2;
    private java.lang.Object start_;
    /**
     * <code>required string start = 2;</code>
     */
    public boolean hasStart() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string start = 2;</code>
     */
    public java.lang.String getStart() {
      java.lang.Object ref = start_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          start_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string start = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStartBytes() {
      java.lang.Object ref = start_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        start_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int END_FIELD_NUMBER = 3;
    private java.lang.Object end_;
    /**
     * <code>required string end = 3;</code>
     */
    public boolean hasEnd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string end = 3;</code>
     */
    public java.lang.String getEnd() {
      java.lang.Object ref = end_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          end_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string end = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEndBytes() {
      java.lang.Object ref = end_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        end_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      start_ = "";
      end_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStart()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEnd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getStartBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEndBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getStartBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEndBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.fedragon.protobuffying.protocol.Protocol.Session parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Session parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Session parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Session parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Session parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Session parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Session parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Session parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Session parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Session parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.fedragon.protobuffying.protocol.Protocol.Session prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuffying.Session}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuffying.Session)
        com.github.fedragon.protobuffying.protocol.Protocol.SessionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.fedragon.protobuffying.protocol.Protocol.internal_static_protobuffying_Session_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.fedragon.protobuffying.protocol.Protocol.internal_static_protobuffying_Session_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.fedragon.protobuffying.protocol.Protocol.Session.class, com.github.fedragon.protobuffying.protocol.Protocol.Session.Builder.class);
      }

      // Construct using com.github.fedragon.protobuffying.protocol.Protocol.Session.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        start_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        end_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.fedragon.protobuffying.protocol.Protocol.internal_static_protobuffying_Session_descriptor;
      }

      public com.github.fedragon.protobuffying.protocol.Protocol.Session getDefaultInstanceForType() {
        return com.github.fedragon.protobuffying.protocol.Protocol.Session.getDefaultInstance();
      }

      public com.github.fedragon.protobuffying.protocol.Protocol.Session build() {
        com.github.fedragon.protobuffying.protocol.Protocol.Session result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.fedragon.protobuffying.protocol.Protocol.Session buildPartial() {
        com.github.fedragon.protobuffying.protocol.Protocol.Session result = new com.github.fedragon.protobuffying.protocol.Protocol.Session(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.start_ = start_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.end_ = end_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.fedragon.protobuffying.protocol.Protocol.Session) {
          return mergeFrom((com.github.fedragon.protobuffying.protocol.Protocol.Session)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.fedragon.protobuffying.protocol.Protocol.Session other) {
        if (other == com.github.fedragon.protobuffying.protocol.Protocol.Session.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasStart()) {
          bitField0_ |= 0x00000002;
          start_ = other.start_;
          onChanged();
        }
        if (other.hasEnd()) {
          bitField0_ |= 0x00000004;
          end_ = other.end_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasStart()) {
          
          return false;
        }
        if (!hasEnd()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.fedragon.protobuffying.protocol.Protocol.Session parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.fedragon.protobuffying.protocol.Protocol.Session) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object start_ = "";
      /**
       * <code>required string start = 2;</code>
       */
      public boolean hasStart() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string start = 2;</code>
       */
      public java.lang.String getStart() {
        java.lang.Object ref = start_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            start_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string start = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStartBytes() {
        java.lang.Object ref = start_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          start_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string start = 2;</code>
       */
      public Builder setStart(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string start = 2;</code>
       */
      public Builder clearStart() {
        bitField0_ = (bitField0_ & ~0x00000002);
        start_ = getDefaultInstance().getStart();
        onChanged();
        return this;
      }
      /**
       * <code>required string start = 2;</code>
       */
      public Builder setStartBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        start_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object end_ = "";
      /**
       * <code>required string end = 3;</code>
       */
      public boolean hasEnd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string end = 3;</code>
       */
      public java.lang.String getEnd() {
        java.lang.Object ref = end_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            end_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string end = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEndBytes() {
        java.lang.Object ref = end_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          end_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string end = 3;</code>
       */
      public Builder setEnd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        end_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string end = 3;</code>
       */
      public Builder clearEnd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        end_ = getDefaultInstance().getEnd();
        onChanged();
        return this;
      }
      /**
       * <code>required string end = 3;</code>
       */
      public Builder setEndBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        end_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuffying.Session)
    }

    static {
      defaultInstance = new Session(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuffying.Session)
  }

  public interface SessionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuffying.Sessions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protobuffying.Session session = 1;</code>
     */
    java.util.List<com.github.fedragon.protobuffying.protocol.Protocol.Session> 
        getSessionList();
    /**
     * <code>repeated .protobuffying.Session session = 1;</code>
     */
    com.github.fedragon.protobuffying.protocol.Protocol.Session getSession(int index);
    /**
     * <code>repeated .protobuffying.Session session = 1;</code>
     */
    int getSessionCount();
    /**
     * <code>repeated .protobuffying.Session session = 1;</code>
     */
    java.util.List<? extends com.github.fedragon.protobuffying.protocol.Protocol.SessionOrBuilder> 
        getSessionOrBuilderList();
    /**
     * <code>repeated .protobuffying.Session session = 1;</code>
     */
    com.github.fedragon.protobuffying.protocol.Protocol.SessionOrBuilder getSessionOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuffying.Sessions}
   */
  public static final class Sessions extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuffying.Sessions)
      SessionsOrBuilder {
    // Use Sessions.newBuilder() to construct.
    private Sessions(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Sessions(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Sessions defaultInstance;
    public static Sessions getDefaultInstance() {
      return defaultInstance;
    }

    public Sessions getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Sessions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                session_ = new java.util.ArrayList<com.github.fedragon.protobuffying.protocol.Protocol.Session>();
                mutable_bitField0_ |= 0x00000001;
              }
              session_.add(input.readMessage(com.github.fedragon.protobuffying.protocol.Protocol.Session.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          session_ = java.util.Collections.unmodifiableList(session_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.fedragon.protobuffying.protocol.Protocol.internal_static_protobuffying_Sessions_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.fedragon.protobuffying.protocol.Protocol.internal_static_protobuffying_Sessions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.fedragon.protobuffying.protocol.Protocol.Sessions.class, com.github.fedragon.protobuffying.protocol.Protocol.Sessions.Builder.class);
    }

    public static com.google.protobuf.Parser<Sessions> PARSER =
        new com.google.protobuf.AbstractParser<Sessions>() {
      public Sessions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Sessions(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Sessions> getParserForType() {
      return PARSER;
    }

    public static final int SESSION_FIELD_NUMBER = 1;
    private java.util.List<com.github.fedragon.protobuffying.protocol.Protocol.Session> session_;
    /**
     * <code>repeated .protobuffying.Session session = 1;</code>
     */
    public java.util.List<com.github.fedragon.protobuffying.protocol.Protocol.Session> getSessionList() {
      return session_;
    }
    /**
     * <code>repeated .protobuffying.Session session = 1;</code>
     */
    public java.util.List<? extends com.github.fedragon.protobuffying.protocol.Protocol.SessionOrBuilder> 
        getSessionOrBuilderList() {
      return session_;
    }
    /**
     * <code>repeated .protobuffying.Session session = 1;</code>
     */
    public int getSessionCount() {
      return session_.size();
    }
    /**
     * <code>repeated .protobuffying.Session session = 1;</code>
     */
    public com.github.fedragon.protobuffying.protocol.Protocol.Session getSession(int index) {
      return session_.get(index);
    }
    /**
     * <code>repeated .protobuffying.Session session = 1;</code>
     */
    public com.github.fedragon.protobuffying.protocol.Protocol.SessionOrBuilder getSessionOrBuilder(
        int index) {
      return session_.get(index);
    }

    private void initFields() {
      session_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getSessionCount(); i++) {
        if (!getSession(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < session_.size(); i++) {
        output.writeMessage(1, session_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < session_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, session_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.fedragon.protobuffying.protocol.Protocol.Sessions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Sessions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Sessions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Sessions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Sessions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Sessions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Sessions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Sessions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Sessions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.fedragon.protobuffying.protocol.Protocol.Sessions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.fedragon.protobuffying.protocol.Protocol.Sessions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuffying.Sessions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuffying.Sessions)
        com.github.fedragon.protobuffying.protocol.Protocol.SessionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.fedragon.protobuffying.protocol.Protocol.internal_static_protobuffying_Sessions_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.fedragon.protobuffying.protocol.Protocol.internal_static_protobuffying_Sessions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.fedragon.protobuffying.protocol.Protocol.Sessions.class, com.github.fedragon.protobuffying.protocol.Protocol.Sessions.Builder.class);
      }

      // Construct using com.github.fedragon.protobuffying.protocol.Protocol.Sessions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSessionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (sessionBuilder_ == null) {
          session_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          sessionBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.fedragon.protobuffying.protocol.Protocol.internal_static_protobuffying_Sessions_descriptor;
      }

      public com.github.fedragon.protobuffying.protocol.Protocol.Sessions getDefaultInstanceForType() {
        return com.github.fedragon.protobuffying.protocol.Protocol.Sessions.getDefaultInstance();
      }

      public com.github.fedragon.protobuffying.protocol.Protocol.Sessions build() {
        com.github.fedragon.protobuffying.protocol.Protocol.Sessions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.fedragon.protobuffying.protocol.Protocol.Sessions buildPartial() {
        com.github.fedragon.protobuffying.protocol.Protocol.Sessions result = new com.github.fedragon.protobuffying.protocol.Protocol.Sessions(this);
        int from_bitField0_ = bitField0_;
        if (sessionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            session_ = java.util.Collections.unmodifiableList(session_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.session_ = session_;
        } else {
          result.session_ = sessionBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.fedragon.protobuffying.protocol.Protocol.Sessions) {
          return mergeFrom((com.github.fedragon.protobuffying.protocol.Protocol.Sessions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.fedragon.protobuffying.protocol.Protocol.Sessions other) {
        if (other == com.github.fedragon.protobuffying.protocol.Protocol.Sessions.getDefaultInstance()) return this;
        if (sessionBuilder_ == null) {
          if (!other.session_.isEmpty()) {
            if (session_.isEmpty()) {
              session_ = other.session_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSessionIsMutable();
              session_.addAll(other.session_);
            }
            onChanged();
          }
        } else {
          if (!other.session_.isEmpty()) {
            if (sessionBuilder_.isEmpty()) {
              sessionBuilder_.dispose();
              sessionBuilder_ = null;
              session_ = other.session_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sessionBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSessionFieldBuilder() : null;
            } else {
              sessionBuilder_.addAllMessages(other.session_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSessionCount(); i++) {
          if (!getSession(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.fedragon.protobuffying.protocol.Protocol.Sessions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.fedragon.protobuffying.protocol.Protocol.Sessions) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.github.fedragon.protobuffying.protocol.Protocol.Session> session_ =
        java.util.Collections.emptyList();
      private void ensureSessionIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          session_ = new java.util.ArrayList<com.github.fedragon.protobuffying.protocol.Protocol.Session>(session_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.github.fedragon.protobuffying.protocol.Protocol.Session, com.github.fedragon.protobuffying.protocol.Protocol.Session.Builder, com.github.fedragon.protobuffying.protocol.Protocol.SessionOrBuilder> sessionBuilder_;

      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public java.util.List<com.github.fedragon.protobuffying.protocol.Protocol.Session> getSessionList() {
        if (sessionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(session_);
        } else {
          return sessionBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public int getSessionCount() {
        if (sessionBuilder_ == null) {
          return session_.size();
        } else {
          return sessionBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public com.github.fedragon.protobuffying.protocol.Protocol.Session getSession(int index) {
        if (sessionBuilder_ == null) {
          return session_.get(index);
        } else {
          return sessionBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public Builder setSession(
          int index, com.github.fedragon.protobuffying.protocol.Protocol.Session value) {
        if (sessionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSessionIsMutable();
          session_.set(index, value);
          onChanged();
        } else {
          sessionBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public Builder setSession(
          int index, com.github.fedragon.protobuffying.protocol.Protocol.Session.Builder builderForValue) {
        if (sessionBuilder_ == null) {
          ensureSessionIsMutable();
          session_.set(index, builderForValue.build());
          onChanged();
        } else {
          sessionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public Builder addSession(com.github.fedragon.protobuffying.protocol.Protocol.Session value) {
        if (sessionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSessionIsMutable();
          session_.add(value);
          onChanged();
        } else {
          sessionBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public Builder addSession(
          int index, com.github.fedragon.protobuffying.protocol.Protocol.Session value) {
        if (sessionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSessionIsMutable();
          session_.add(index, value);
          onChanged();
        } else {
          sessionBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public Builder addSession(
          com.github.fedragon.protobuffying.protocol.Protocol.Session.Builder builderForValue) {
        if (sessionBuilder_ == null) {
          ensureSessionIsMutable();
          session_.add(builderForValue.build());
          onChanged();
        } else {
          sessionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public Builder addSession(
          int index, com.github.fedragon.protobuffying.protocol.Protocol.Session.Builder builderForValue) {
        if (sessionBuilder_ == null) {
          ensureSessionIsMutable();
          session_.add(index, builderForValue.build());
          onChanged();
        } else {
          sessionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public Builder addAllSession(
          java.lang.Iterable<? extends com.github.fedragon.protobuffying.protocol.Protocol.Session> values) {
        if (sessionBuilder_ == null) {
          ensureSessionIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, session_);
          onChanged();
        } else {
          sessionBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public Builder clearSession() {
        if (sessionBuilder_ == null) {
          session_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sessionBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public Builder removeSession(int index) {
        if (sessionBuilder_ == null) {
          ensureSessionIsMutable();
          session_.remove(index);
          onChanged();
        } else {
          sessionBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public com.github.fedragon.protobuffying.protocol.Protocol.Session.Builder getSessionBuilder(
          int index) {
        return getSessionFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public com.github.fedragon.protobuffying.protocol.Protocol.SessionOrBuilder getSessionOrBuilder(
          int index) {
        if (sessionBuilder_ == null) {
          return session_.get(index);  } else {
          return sessionBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public java.util.List<? extends com.github.fedragon.protobuffying.protocol.Protocol.SessionOrBuilder> 
           getSessionOrBuilderList() {
        if (sessionBuilder_ != null) {
          return sessionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(session_);
        }
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public com.github.fedragon.protobuffying.protocol.Protocol.Session.Builder addSessionBuilder() {
        return getSessionFieldBuilder().addBuilder(
            com.github.fedragon.protobuffying.protocol.Protocol.Session.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public com.github.fedragon.protobuffying.protocol.Protocol.Session.Builder addSessionBuilder(
          int index) {
        return getSessionFieldBuilder().addBuilder(
            index, com.github.fedragon.protobuffying.protocol.Protocol.Session.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuffying.Session session = 1;</code>
       */
      public java.util.List<com.github.fedragon.protobuffying.protocol.Protocol.Session.Builder> 
           getSessionBuilderList() {
        return getSessionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.github.fedragon.protobuffying.protocol.Protocol.Session, com.github.fedragon.protobuffying.protocol.Protocol.Session.Builder, com.github.fedragon.protobuffying.protocol.Protocol.SessionOrBuilder> 
          getSessionFieldBuilder() {
        if (sessionBuilder_ == null) {
          sessionBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.github.fedragon.protobuffying.protocol.Protocol.Session, com.github.fedragon.protobuffying.protocol.Protocol.Session.Builder, com.github.fedragon.protobuffying.protocol.Protocol.SessionOrBuilder>(
                  session_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          session_ = null;
        }
        return sessionBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuffying.Sessions)
    }

    static {
      defaultInstance = new Sessions(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuffying.Sessions)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuffying_Session_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuffying_Session_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuffying_Sessions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuffying_Sessions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/protobuf/session.proto\022\rproto" +
      "buffying\"1\n\007Session\022\n\n\002id\030\001 \002(\005\022\r\n\005start" +
      "\030\002 \002(\t\022\013\n\003end\030\003 \002(\t\"3\n\010Sessions\022\'\n\007sessi" +
      "on\030\001 \003(\0132\026.protobuffying.SessionB6\n*com." +
      "github.fedragon.protobuffying.protocolB\010" +
      "Protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuffying_Session_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuffying_Session_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuffying_Session_descriptor,
        new java.lang.String[] { "Id", "Start", "End", });
    internal_static_protobuffying_Sessions_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuffying_Sessions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuffying_Sessions_descriptor,
        new java.lang.String[] { "Session", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
